version: "3.8"
networks:
  app_network:
    driver: host
services:
  db:
    build:
      context: .
      dockerfile: docker/db.dockerfile
    ports:
      - "5432:5432"
    env_file:
      - .env
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  app:
    build:
      context: .
      dockerfile: docker/app.dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
  app_test:
    build:
      context: .
      dockerfile: docker/test.dockerfile
    depends_on:
      - db
      - app
      - redis
    env_file: .env
    volumes:
      - .:/app
    environment:
      POSTGRES_URL: postgresql://postgres:1234@db:5432/postgres
